# Config file for [readme-md-cli](https://www.npmjs.com/package/readme-md-cli).
---
badges:
  style: flat-square
  render:
    - github-actions
    - license
    - node.js
    - npm
see-also:
  readme-md-cli: https://www.npmjs.com/package/readme-md-cli
  "I programmed in TypeScript like in Haskell (Lazy Evaluation)": https://www.youtube.com/watch?v=E5yAoMaVCp0
  lazy-evaluation: https://ru.wikipedia.org/wiki/%D0%9B%D0%B5%D0%BD%D0%B8%D0%B2%D1%8B%D0%B5_%D0%B2%D1%8B%D1%87%D0%B8%D1%81%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F
